version: '3'
services:
#  it-chain:
#    build: .
#    ports:
#     - "13759:13759"
#    depends_on:
#     - rabbitmq
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15671:15672"
      - "5671:5672"