database:
  type: leveldb
  leveldb:
    defaultPath: .it-chain/leveldb

key:
  type: RSA
  defaultPath: .it-chain/

ledger:
  defaultPath: .it-chain/ledger

txDatabase:
  defaultPath: .it-chain/tx

smartContract:
  defaultPath: .it-chain/.constracts
  githubID: steve@buzzni.com
  githubPassword: itchain123
  githubAccessToken: 1a8ae688db783f63c2494d59f971b2eed5399b1d
  TmpDir: /tmp
  WorldStateDB_OnDoker: /go/src/worldstatedb

batchTimer:
  pushPeerTable: 5
  sendTransaction: 5

bootNode:
  ip: 127.0.0.1:4444

node:
  ip: 127.0.0.1:4444

consensus:
  batchTime: 3
  maxTransactions: 100
